---
title: "nphRshiny Examples"
author: "Philip He"
date: "2021-07-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## wlr.power.maxcombo() Function

```{r}
library(nphRshiny)
```

```{r}
#Distributions for both arms
m0 = 12; #median OS for control arm
lambda0 = log(2) / m0
h0 = function(t){lambda0}; 
S0 = function(t){exp(-lambda0 * t)}
HRd = 0.60 #hazard ratio after delay

h.D3=function(t){lambda0*as.numeric(t<3)+HRd*lambda0*as.numeric(t>=3)}
c3 = exp(-3*lambda0*(1-HRd)); 
S.D3 = function(t){S0(t)*as.numeric(t<3)+c3*exp(-HRd*lambda0*t)*as.numeric(t>=3)}

#Define weight functions for weighted log-rank tests
lr = function(s){1}
fh01 = function(s){(1-s)}
fh11 = function(s){s*(1-s)}

#Enrollment
Lambda = function(t){(t/18)^1.5*as.numeric(t <= 18) + as.numeric(t > 18)};
G0 = function(t){0}; G1 = function(t){0}; 
  
```

```{r}

#Schoenfeld method with power based on covariance matrix under H0
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(fh01)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "Schoenfeld", cov.method = "H0")
  
```

```{r}
  
#Schoenfeld method with power based on covariance matrix under H1
#####ERROR: cov.method = "H1" error

#wlr.power.maxcombo(DCO = c(24, 36),  
#  alpha=c(0.01, 0.04)/2, 
#  r = 1, n = 500, 
#  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
#  f.ws = list(IA1 = list(lr), FA=list(fh01)), 
#  Lambda=Lambda, G0=G0, G1=G1,
#  mu.method = "Schoenfeld", cov.method = "H1")
  
```

```{r}
  
#Schoenfeld method with power based on covariance matrix under H1 in Local Alternative (simplified)
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(fh01)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "Schoenfeld", cov.method = "H1.LA")   
  
```

```{r}
     
#Mean(Z) under H1 with power based on covariance matrix under H0
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(fh01)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "H1", cov.method = "H0")
  
```

```{r}
  
#Mean(Z) under H1 with power based on covariance matrix under H1
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(fh01)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "H1", cov.method = "H1.LA")
  
```

```{r}
  
#Mean(Z) under H1 with power based on covariance matrix under H1 in Local Alternative (simplified)
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(fh01)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "H1", cov.method = "H1.LA")   
  
```

```{r}

#max-combo(logrank, FH11) at FA   
#Mean(Z) under H1 with power based on covariance matrix under H1 in Local Alternative (simplified)
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(lr, fh11)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "Schoenfeld", cov.method = "H1.LA")
  
```

```{r}
#max-combo(logrank, FH11) at FA   
#Mean(Z) under H1 with power based on covariance matrix under H1
wlr.power.maxcombo(DCO = c(24, 36),  
  alpha=c(0.01, 0.04)/2, 
  r = 1, n = 500, 
  h0 = h0, S0=S0,h1 = h.D3, S1= S.D3, 
  f.ws = list(IA1 = list(lr), FA=list(lr, fh11)), 
  Lambda=Lambda, G0=G0, G1=G1,
  mu.method = "H1", cov.method = "H0")   

```

